- alias: Single click toggle Justin's light
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001562c66
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: group.justins_bedroom


- alias: Motion detected turn on shower room light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001db53b2
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.showeroom

- alias: No motion for 5 minutes turn off shower room light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001db53b2
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id: light.showeroom

