homeassistant:
  name: TechVille
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature

# Enables a map showing the location of tracked devices
#map:

# Track the sun
#sun:

# Cloud
cloud:
  alexa:
    filter:
      exclude_entities:
        - sensor.dark_sky_summary
        - sensor.dark_sky_daily_high_temperature
        - sensor.dark_sky_daily_low_temperature
        - sensor.dark_sky_precip
        - sensor.dark_sky_precip_probability
        - sensor.dark_sky_temperature
    entity_config:
      group.tv:
        name: TV lights
        description: Control ledstrips for the TV

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

hue:
  bridges:
    - host: 192.168.31.154
      allow_unreachable: true
      allow_hue_groups: false

sensor:
# Weather
  - platform: darksky
    api_key: !secret darksky_api
    units: auto
    monitored_conditions:
      - summary
      - temperature
      - temperature_max
      - temperature_min
      - precip_type
      - precip_probability
# Air quality
  - platform: waqi
    token: !secret token_waqi
    locations:
      - Zhongshan, Taiwan

# Yeelight
light:
  - platform: yeelight
    devices:
      192.168.31.81:
        name: TV up
      192.168.31.184:
        name: TV back
      192.168.31.99:
        name: Bed T
      192.168.31.8:
        name: Bed L
      192.168.31.17:
        name: Bed under
      192.168.31.117:
        name: Showeroom
      192.168.31.76:
        name: Bathroom
