esphome:
  name: esp_camera
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "HoytManor"
  password: "Hoytmanorpass"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_camera:
  name: ESP Camera
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO13
    scl: GPIO12
  data_pins: [GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin: GPIO27
  href_pin: GPIO25
  pixel_clock_pin: GPIO19
  max_framerate: 5 fps
  jpeg_quality: 10
  vertical_flip: false
  
  
  
i2c:
  sda: GPIO21
  scl: GPIO22

#font:
#  - file: "Ubuntu-Regular.ttf"
#    id: ubuntu
#    size: 20

#display:
#  - platform: ssd1306_i2c
#    model: "SSD1306 128x64"
#    address: 0x3C
#    lambda: |-
#      it.print(0, 0, id(ubuntu), "Hello World!");
  
# sensor:
#   - platform: bme280
#     temperature:
#       name: "BME280 Temperature"
#       oversampling: 16x
#     pressure:
#       name: "BME280 Pressure"
#     humidity:
#       name: "BME280 Humidity"
#     address: 0x77
#     update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO33
    name: "ESP PIR Sensor"
    device_class: motion